import {
    BadgeDollarSign,
    BarChart3,
    BookOpen,
    BookOpenCheck,
    Brain,
    CalendarDays,
    Car,
    CheckCircle2,
    Circle,
    CircleHelp,
    ClipboardCheck,
    Compass,
    Flag,
    Gamepad2,
    GraduationCap,
    HeartPulse,
    Home,
    Hourglass,
    House,
    Lightbulb,
    ListChecks,
    Lock,
    Menu,
    Moon,
    NotebookTabs,
    PiggyBank,
    Scale,
    Search,
    SearchX,
    ShieldAlert,
    ShoppingBag,
    Sparkles,
    Target,
    TrendingUp,
    Trophy,
    UserCircle,
    Utensils,
    Wallet,
    Zap,
} from "lucide-react";

const icons = {
    BadgeDollarSign,
    BarChart3,
    BookOpen,
    BookOpenCheck,
    Brain,
    CalendarDays,
    Car,
    ChartNoAxesColumnIncreasing: BarChart3,
    CheckCircle2,
    Circle,
    CircleHelp,
    ClipboardCheck,
    Compass,
    Flag,
    Gamepad2,
    GraduationCap,
    HeartPulse,
    Home,
    Hourglass,
    House,
    Lightbulb,
    ListChecks,
    Lock,
    Menu,
    Moon,
    NotebookTabs,
    PiggyBank,
    Scale,
    Search,
    SearchX,
    ShieldAlert,
    ShoppingBag,
    Sparkles,
    Target,
    TrendingUp,
    Trophy,
    UserCircle,
    Utensils,
    Wallet,
    Zap,
};

export default function AppIcon({ name = "Circle", className = "h-5 w-5", strokeWidth = 2.25, ...props }) {
    const Icon = icons[name] || Circle;
    return <Icon className={className} strokeWidth={strokeWidth} aria-hidden="true" {...props} />;
}
