export const APP_CONFIG = {
    appName: "Prototipo",
    appSlogan: "Aprende finanzas y construye mejores habitos con tu dinero",
    colors: {
        yellow: "#ffcc2a",
        black: "#010209",
        sky: "#c9e4f9",
        red: "#fe5d4b",
        green: "#32b984",
        blue: "#1e67b8",
    },
};

export const TRIAGE_QUESTIONS = [
    {
        id: "q1",
        question: "¿Que tan comodo te sientes manejando tu dinero?",
        description: "Esto nos ayuda a personalizar tu experiencia.",
        options: [
            { id: "q1_a", label: "Me cuesta mucho organizarme", score: 1, interestTag: "basic_money_management" },
            { id: "q1_b", label: "Se algunas cosas, pero no soy constante", score: 2, interestTag: "habits" },
            { id: "q1_c", label: "Tengo un sistema basico para organizarme", score: 3, interestTag: "planning" },
            { id: "q1_d", label: "Manejo presupuesto, ahorro y metas", score: 4, interestTag: "advanced_planning" },
        ],
    },
    {
        id: "q2",
        question: "¿Que haces cuando recibes dinero?",
        description: "Queremos entender tus habitos actuales.",
        options: [
            { id: "q2_a", label: "Lo gasto sin planear mucho", score: 1, interestTag: "spending_control" },
            { id: "q2_b", label: "Pago cosas importantes y luego miro que queda", score: 2, interestTag: "budgeting" },
            { id: "q2_c", label: "Separo una parte para ahorrar", score: 3, interestTag: "saving" },
            { id: "q2_d", label: "Lo distribuyo entre presupuesto, ahorro e inversion", score: 4, interestTag: "planning" },
        ],
    },
    {
        id: "q3",
        question: "¿Sabes cuanto gastas al mes?",
        description: "El control del gasto es una base importante.",
        options: [
            { id: "q3_a", label: "No, casi nunca lo reviso", score: 1, interestTag: "expense_tracking" },
            { id: "q3_b", label: "Tengo una idea aproximada", score: 2, interestTag: "expense_tracking" },
            { id: "q3_c", label: "Si, lo anoto algunas veces", score: 3, interestTag: "budgeting" },
            { id: "q3_d", label: "Si, llevo control detallado", score: 4, interestTag: "advanced_planning" },
        ],
    },
    {
        id: "q4",
        question: "¿Tienes una meta financiera activa?",
        description: "Por ejemplo, ahorrar, pagar una deuda o controlar gastos.",
        options: [
            { id: "q4_a", label: "No tengo ninguna", score: 1, interestTag: "goal_setting" },
            { id: "q4_b", label: "Tengo una idea, pero no la he organizado", score: 2, interestTag: "goal_setting" },
            { id: "q4_c", label: "Si, tengo una meta definida", score: 3, interestTag: "saving" },
            { id: "q4_d", label: "Si, tengo varias metas con seguimiento", score: 4, interestTag: "advanced_planning" },
        ],
    },
    {
        id: "q5",
        question: "¿Que tema te interesa aprender primero?",
        description: "Te recomendaremos rutas segun tus intereses.",
        options: [
            { id: "q5_a", label: "Aprender a ahorrar", score: 2, interestTag: "saving" },
            { id: "q5_b", label: "Controlar gastos impulsivos", score: 2, interestTag: "spending_control" },
            { id: "q5_c", label: "Crear un presupuesto", score: 2, interestTag: "budgeting" },
            { id: "q5_d", label: "Tomar mejores decisiones financieras", score: 2, interestTag: "decision_making" },
        ],
    },
    {
        id: "q6",
        question: "¿Que tan dificil te parece ahorrar?",
        description: "Esto ayuda a definir el tipo de metas iniciales.",
        options: [
            { id: "q6_a", label: "Muy dificil, casi nunca ahorro", score: 1, interestTag: "saving" },
            { id: "q6_b", label: "A veces ahorro, pero no soy constante", score: 2, interestTag: "habits" },
            { id: "q6_c", label: "Puedo ahorrar si tengo una meta clara", score: 3, interestTag: "goal_setting" },
            { id: "q6_d", label: "Ahorro regularmente", score: 4, interestTag: "advanced_planning" },
        ],
    },
    {
        id: "q7",
        question: "Cuando compras algo no planeado, ¿que suele pasar?",
        description: "Identificaremos oportunidades de autocontrol financiero.",
        options: [
            { id: "q7_a", label: "Lo hago con frecuencia y luego me arrepiento", score: 1, interestTag: "spending_control" },
            { id: "q7_b", label: "A veces pasa, pero intento corregirlo", score: 2, interestTag: "habits" },
            { id: "q7_c", label: "Comparo opciones antes de comprar", score: 3, interestTag: "decision_making" },
            { id: "q7_d", label: "Uso reglas claras antes de gastar", score: 4, interestTag: "advanced_planning" },
        ],
    },
];

export const GOAL_TEMPLATES = [
    {
        id: "template_save_10k_week",
        title: "Ahorrar $10.000 esta semana",
        description: "Empieza con una meta pequena y alcanzable.",
        type: "saving_amount",
        suggestedLevel: "beginner",
        tags: ["saving", "habits"],
        iconKey: "Wallet",
        defaultTargetAmount: 10000,
        defaultDurationDays: 7,
        defaultTargetLessons: 0,
        difficulty: "easy",
    },
    {
        id: "template_track_expenses_3_days",
        title: "Registrar gastos durante 3 dias",
        description: "Observa en que se va tu dinero antes de intentar cambiarlo.",
        type: "habit_streak",
        suggestedLevel: "beginner",
        tags: ["expense_tracking", "habits"],
        iconKey: "ClipboardCheck",
        defaultTargetAmount: 0,
        defaultDurationDays: 3,
        defaultTargetLessons: 0,
        difficulty: "easy",
    },
    {
        id: "template_reduce_entertainment",
        title: "Reducir gastos de entretenimiento",
        description: "Controla pequenos gastos que se acumulan durante la semana.",
        type: "expense_limit",
        suggestedLevel: "intermediate",
        tags: ["spending_control", "budgeting"],
        iconKey: "Gamepad2",
        defaultTargetAmount: 50000,
        defaultDurationDays: 7,
        defaultTargetLessons: 0,
        difficulty: "medium",
    },
    {
        id: "template_complete_3_lessons",
        title: "Completar 3 lecciones esta semana",
        description: "Construye conocimiento financiero paso a paso.",
        type: "lesson_completion",
        suggestedLevel: "beginner",
        tags: ["learning", "habits"],
        iconKey: "BookOpenCheck",
        defaultTargetAmount: 0,
        defaultDurationDays: 7,
        defaultTargetLessons: 3,
        difficulty: "easy",
    },
    {
        id: "template_cash_control_week",
        title: "Revisar gastos cada noche",
        description: "Cierra el dia revisando si tus gastos fueron necesarios o impulsivos.",
        type: "habit_streak",
        suggestedLevel: "intermediate",
        tags: ["expense_tracking", "spending_control"],
        iconKey: "Moon",
        defaultTargetAmount: 0,
        defaultDurationDays: 7,
        defaultTargetLessons: 0,
        difficulty: "medium",
    },
];

export const LEARNING_PATHS = [
    {
        id: "path_saving_expenses",
        title: "Ahorro y gastos",
        description: "Aprende a identificar en que se va tu dinero y como empezar a ahorrar.",
        level: "beginner",
        tags: ["saving", "expense_tracking", "spending_control", "habits"],
        iconKey: "PiggyBank",
        color: "#1e67b8",
        lessons: [
            {
                id: "lesson_where_money_goes",
                pathId: "path_saving_expenses",
                order: 1,
                title: "¿En que se va tu dinero?",
                description: "Reconoce gastos cotidianos y detecta una oportunidad de mejora.",
                estimatedMinutes: 5,
                xpReward: 10,
                steps: [
                    { id: "l1_s1", type: "content", title: "Leccion 1", body: "Entender tus gastos es el primer paso para ahorrar mejor. Hoy solo necesitas mirar una categoria pequena.", iconKey: "PiggyBank" },
                    { id: "l1_s2", type: "interaction", title: "Categorias de gasto", body: "Todos gastamos en distintas cosas. Lo importante es reconocer cuales se llevan mas dinero.", options: [{ id: "food", label: "Comida", iconKey: "Utensils" }, { id: "transport", label: "Transporte", iconKey: "Car" }, { id: "entertainment", label: "Entretenimiento", iconKey: "Gamepad2" }] },
                    { id: "l1_s3", type: "question", title: "Ahora aplicalo a tu caso", body: "¿Cual de estos gastos crees que podrias reducir esta semana?", options: [{ id: "food", label: "Comida", iconKey: "Utensils" }, { id: "transport", label: "Transporte", iconKey: "Car" }, { id: "entertainment", label: "Entretenimiento", iconKey: "Gamepad2" }, { id: "shopping", label: "Compras impulsivas", iconKey: "ShoppingBag" }] },
                    { id: "l1_s4", type: "result", title: "Tu principal oportunidad de mejora", body: "Podrias empezar reduciendo pequenos gastos esta semana. Antes: ahorro bajo. Despues: podrias ahorrar $10.000 o mas con una accion simple.", iconKey: "Target" },
                    { id: "l1_s5", type: "action", title: "Convierte esto en un habito", body: "Elige una accion concreta para esta semana.", options: [{ id: "template_reduce_entertainment", label: "Reducir gastos de entretenimiento", iconKey: "Gamepad2" }, { id: "template_track_expenses_3_days", label: "Registrar gastos durante 3 dias", iconKey: "ClipboardCheck" }, { id: "template_save_10k_week", label: "Ahorrar $10.000 esta semana", iconKey: "Wallet" }] },
                    { id: "l1_s6", type: "final", title: "Vas por buen camino", body: "Leccion completada. Ya diste tu primer paso y puedes convertir este aprendizaje en una meta real.", iconKey: "CheckCircle2" },
                ],
            },
            {
                id: "lesson_needs_wants",
                pathId: "path_saving_expenses",
                order: 2,
                title: "Necesidad o deseo",
                description: "Aprende a distinguir gastos necesarios y gastos que puedes aplazar.",
                estimatedMinutes: 4,
                xpReward: 10,
                steps: [
                    { id: "l2_s1", type: "content", title: "Antes de gastar", body: "Una necesidad sostiene tu vida diaria. Un deseo puede mejorar tu experiencia, pero normalmente puede esperar.", iconKey: "Brain" },
                    { id: "l2_s2", type: "question", title: "Clasifica rapido", body: "Si tienes poco dinero esta semana, ¿que gasto revisarias primero?", options: [{ id: "rent", label: "Arriendo o transporte obligatorio", iconKey: "Home" }, { id: "snacks", label: "Snacks y compras pequenas", iconKey: "ShoppingBag" }, { id: "medicine", label: "Medicamentos", iconKey: "HeartPulse" }] },
                    { id: "l2_s3", type: "result", title: "Respuesta sugerida", body: "Los snacks y compras pequenas suelen ser deseos. Reducirlos no elimina una necesidad, pero libera dinero.", iconKey: "Lightbulb" },
                    { id: "l2_s4", type: "action", title: "Accion recomendada", body: "Registra tus gastos 3 dias para detectar deseos repetidos.", options: [{ id: "template_track_expenses_3_days", label: "Crear meta: registrar gastos 3 dias", iconKey: "ClipboardCheck" }] },
                    { id: "l2_s5", type: "final", title: "Leccion completada", body: "Ahora tienes una regla simple: primero necesidades, luego deseos.", iconKey: "CheckCircle2" },
                ],
            },
            {
                id: "lesson_first_small_goal",
                pathId: "path_saving_expenses",
                order: 3,
                title: "Tu primera meta pequena",
                description: "Convierte una intencion de ahorro en una meta medible.",
                estimatedMinutes: 4,
                xpReward: 12,
                steps: [
                    { id: "l3_s1", type: "content", title: "Metas pequenas", body: "Una meta pequena es mas facil de cumplir y te ayuda a crear confianza.", iconKey: "Flag" },
                    { id: "l3_s2", type: "interaction", title: "Formula simple", body: "Meta = monto + fecha + accion. Ejemplo: ahorrar $10.000 esta semana reduciendo un gasto pequeno.", options: [{ id: "amount", label: "Monto", iconKey: "BadgeDollarSign" }, { id: "date", label: "Fecha", iconKey: "CalendarDays" }, { id: "action", label: "Accion", iconKey: "ListChecks" }] },
                    { id: "l3_s3", type: "action", title: "Crea una meta real", body: "Puedes empezar ahora con una meta corta.", options: [{ id: "template_save_10k_week", label: "Ahorrar $10.000 esta semana", iconKey: "Wallet" }] },
                    { id: "l3_s4", type: "final", title: "Listo", body: "Una meta clara se puede medir y mejorar.", iconKey: "Target" },
                ],
            },
        ],
    },
    {
        id: "path_budgeting",
        title: "Presupuesto personal",
        description: "Organiza tus ingresos, gastos y dinero disponible.",
        level: "intermediate",
        tags: ["budgeting", "planning", "expense_tracking"],
        iconKey: "ChartNoAxesColumnIncreasing",
        color: "#32b984",
        lessons: [
            {
                id: "lesson_budget_intro",
                pathId: "path_budgeting",
                order: 1,
                title: "¿Que es un presupuesto?",
                description: "Aprende a organizar ingresos y gastos sin complicarte.",
                estimatedMinutes: 5,
                xpReward: 12,
                steps: [
                    { id: "b1_s1", type: "content", title: "Presupuesto personal", body: "Un presupuesto es un plan para decidir antes de gastar. No es castigo: es claridad.", iconKey: "NotebookTabs" },
                    { id: "b1_s2", type: "interaction", title: "Tres bloques", body: "Divide tu dinero en gastos necesarios, ahorro y gastos flexibles.", options: [{ id: "needs", label: "Necesarios", iconKey: "House" }, { id: "save", label: "Ahorro", iconKey: "Wallet" }, { id: "flex", label: "Flexibles", iconKey: "BadgeDollarSign" }] },
                    { id: "b1_s3", type: "question", title: "Pregunta rapida", body: "¿Que deberias separar primero al recibir dinero?", options: [{ id: "leftover", label: "Lo que sobre al final", iconKey: "CircleHelp" }, { id: "saving", label: "Una parte para ahorro", iconKey: "Wallet" }, { id: "impulse", label: "Compras impulsivas", iconKey: "ShoppingBag" }] },
                    { id: "b1_s4", type: "result", title: "Respuesta sugerida", body: "Separar ahorro al inicio te ayuda a no depender de lo que sobre.", iconKey: "CheckCircle2" },
                    { id: "b1_s5", type: "action", title: "Llevalo a una meta", body: "Crea un habito de revision semanal.", options: [{ id: "template_cash_control_week", label: "Revisar gastos cada noche", iconKey: "Moon" }] },
                    { id: "b1_s6", type: "final", title: "Buen avance", body: "Ya conoces una estructura simple para tu presupuesto.", iconKey: "ChartNoAxesColumnIncreasing" },
                ],
            },
            {
                id: "lesson_fixed_variable",
                pathId: "path_budgeting",
                order: 2,
                title: "Gastos fijos y variables",
                description: "Identifica que gastos puedes ajustar mas facilmente.",
                estimatedMinutes: 4,
                xpReward: 10,
                steps: [
                    { id: "b2_s1", type: "content", title: "Fijos vs variables", body: "Los fijos se repiten y cambian poco. Los variables dependen de tus decisiones semanales.", iconKey: "Search" },
                    { id: "b2_s2", type: "question", title: "Detecta el ajuste", body: "¿Cual suele ser mas facil ajustar esta semana?", options: [{ id: "rent", label: "Arriendo", iconKey: "House" }, { id: "snacks", label: "Comidas fuera", iconKey: "Utensils" }, { id: "tuition", label: "Matricula", iconKey: "GraduationCap" }] },
                    { id: "b2_s3", type: "result", title: "Oportunidad", body: "Los gastos variables suelen ofrecer cambios pequenos pero rapidos.", iconKey: "Lightbulb" },
                    { id: "b2_s4", type: "final", title: "Completado", body: "Ya puedes detectar por donde ajustar primero.", iconKey: "CheckCircle2" },
                ],
            },
        ],
    },
    {
        id: "path_decision_making",
        title: "Decisiones financieras inteligentes",
        description: "Aprende a tomar mejores decisiones antes de gastar.",
        level: "advanced",
        tags: ["decision_making", "advanced_planning", "planning"],
        iconKey: "Brain",
        color: "#ffcc2a",
        lessons: [
            {
                id: "lesson_opportunity_cost",
                pathId: "path_decision_making",
                order: 1,
                title: "Costo de oportunidad",
                description: "Entiende que eliges cada vez que gastas.",
                estimatedMinutes: 5,
                xpReward: 14,
                steps: [
                    { id: "d1_s1", type: "content", title: "Cada decision tiene costo", body: "Si gastas hoy, quiza renuncias a ahorrar, invertir o cumplir otra meta.", iconKey: "Scale" },
                    { id: "d1_s2", type: "question", title: "Piensa antes de comprar", body: "Antes de una compra impulsiva, ¿que pregunta ayuda mas?", options: [{ id: "cheap", label: "¿Es barato?", iconKey: "BadgeDollarSign" }, { id: "goal", label: "¿Me acerca o me aleja de mi meta?", iconKey: "Target" }, { id: "fast", label: "¿Lo puedo comprar rapido?", iconKey: "Zap" }] },
                    { id: "d1_s3", type: "result", title: "Mejor pregunta", body: "Preguntar si te acerca a tu meta convierte una compra en una decision consciente.", iconKey: "Compass" },
                    { id: "d1_s4", type: "final", title: "Decision inteligente", body: "Ya tienes una regla para pausar antes de gastar.", iconKey: "CheckCircle2" },
                ],
            },
            {
                id: "lesson_wait_or_buy",
                pathId: "path_decision_making",
                order: 2,
                title: "Comprar ahora o esperar",
                description: "Usa una pausa corta para evitar compras impulsivas.",
                estimatedMinutes: 4,
                xpReward: 12,
                steps: [
                    { id: "d2_s1", type: "content", title: "La pausa de 24 horas", body: "Para compras no urgentes, esperar 24 horas puede reducir impulsos.", iconKey: "Hourglass" },
                    { id: "d2_s2", type: "action", title: "Convierte la pausa en habito", body: "Registra durante 3 dias las compras que pausaste.", options: [{ id: "template_track_expenses_3_days", label: "Registrar gastos durante 3 dias", iconKey: "ClipboardCheck" }] },
                    { id: "d2_s3", type: "final", title: "Completado", body: "Esperar tambien es una decision financiera.", iconKey: "CheckCircle2" },
                ],
            },
        ],
    },
];
